config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :recipes, except: [ :update ] do
    resources :ingredients, controller: 'ingredients', except: [ :index, :show ], shallow: true
  end
  resources :foods, except: [ :show, :update]
  
  get 'general_shopping_list', to: 'general_shopping_list#index', as: :shopping_list
  get 'public_recipes', to: 'recipes#public_recipes', as: :public_recipes

  root 'recipes#public_recipes'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Food
    can :read, Recipe, public: true
    can :manage, Food, user: user
    can :manage, Recipe, user: user
    can :manage, Inventory, user: user
    return unless user

    can :manage, Ingredient if user # TODO: handle Ingredient permissions correctly
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :foods_inventories
  has_many :recipes, through: :ingredients
  has_many :inventories, through: :foods_inventories

  validates :name, presence: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true, inclusion: { in: %w[kg units l ml cl g] }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/foods_inventory.rb
class FoodsInventory < ApplicationRecord
  belongs_to :food
  belongs_to :inventory

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/foods_recipe.rb
class FoodsRecipe < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  self.table_name = 'foods_recipes'
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :foods_inventories
  has_many :foods, through: :foods_inventories

  validates :name, presence: true, length: { maximum: 250 }
end

app/models/inventory_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :foods, through: :ingredients

  validates :name, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :public, presence: true, inclusion: [true, false]

  def add_ingredient!(food, quantity)
    already_exists = foods.find_by(name: food.name)
    if already_exists
      ingredients.create!(food: already_exists, quantity: quantity) unless already_exists
    else
      ingredients.create!(food: food, quantity: quantity) unless already_exists
    end
  end

  def add_ingredient(food, quantity)
    already_exists = foods.find_by(name: food.name)
    created = ingredients.create(food: food, quantity: quantity) unless already_exists
    created
  end

  def total_food_items
    foods.size
  end

  def total_price
    total = 0
    ingredients.each do |ingredient|
      total += ingredient.food.price * ingredient.quantity
    end
    total
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :name, presence: true

  has_many :recipes
  has_many :foods
  has_many :inventories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource

  def index
    @foods = current_user.foods
  end

  def new; end

  def create
    new_food = current_user.foods.new(food_params)
    if new_food.save
      flash[:success] = 'You successfully added a food item'
      redirect_to foods_url
    else
      flash.now[:error] = 'Error: You could not add a food item'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy!
    flash[:success] = 'You deleted this food item'
    redirect_to foods_url
  end

  private

  def food_params
    params.require(:add_food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  # load_and_authorize_resource
  before_action :retrieve_missing_items
  def index
    retrieve_missing_items
  end

  private

  def retrieve_missing_items
    id = current_user.id
    sql = "select foods_inventories.quantity,
          foods_recipes.quantity, foods.name,
          foods.price, foods.measurement_unit from recipes join foods_recipes on foods_recipes.recipe_id = recipes.id
          left join foods on foods.id = foods_recipes.food_id
          join foods_inventories on foods_inventories.food_id = foods.id where recipes.user_id = #{id}"
    records_array = ActiveRecord::Base.connection.execute(sql)

    list_items = records_array.values

    @missing_items = list_items.select do |list_item|
      list_item[0] < list_item[1]
    end

    @missing_items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @recipe = current_recipe
    @ingredient = Ingredient.new(recipe: @recipe)
  end

  def create
    food = Food.create!(user: current_user, **food_params)
    current_recipe.add_ingredient!(food, ingredient_params[:quantity])
    flash[:notice] = 'Added ingredient!'
    redirect_to recipe_url(current_recipe)
  end

  def edit
    # TODO: authorize! :edit, @post
    @ingredient = current_ingredient
  end

  def update
    # TODO: authorize! :edit, @post
    ingredient = current_ingredient
    ingredient.update!(ingredient_params)
    redirect_to recipe_url(ingredient.recipe_id)
    puts params
  end

  def destroy
    ingredient = current_ingredient
    ingredient.destroy!
    flash[:notice] = 'Deleted ingredient!'
    redirect_to recipe_url(ingredient.recipe_id)
  end

  private

  def current_recipe
    Recipe.find(params[:recipe_id])
  end

  def current_ingredient
    Ingredient.find(params[:id])
  end

  def food_params
    params.require(:ingredient).permit(:name, :price, :measurement_unit)
  end

  def ingredient_params
    params.require(:ingredient).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource expect: :public_recipes
  skip_before_action :authenticate_user!, only: :public_recipes

  def create; end

  def new; end

  def index
    @recipes = current_user.recipes.includes(:foods)
  end

  def show; end

  def destroy
    @recipe.destroy!
    flash[:notice] = 'Deleted Recipe!'
    redirect_to recipes_url
  end

  def public_recipes
    @recipes = Recipe.includes(:user, :foods).where(public: true)
  end

  def new_ingredient; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/index.html.erb
<main>
  <div class="add-food-div d-flex">
    <%= link_to 'Add Food', new_food_url, class: 'button add-food d-flex' %>
  </div>

  <table>
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Unit Price ($)</th>
      <th>Actions</th>
    </tr>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= food.price %></td>
        <td><%= link_to 'Delete', food_url(food),
              method: :delete,
              class: 'button',
              data: {confirm: 'Are You Sure You Want to Delete This Food Item'}
              %>
        </td>
      </tr>
    <% end %>
  </table>
</main>

app/views/foods/new.html.erb
<%= form_with url: foods_path, method: :post, local: true, scope: :add_food do |form| %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit %><br>
    <%= form.select :measurement_unit, %w[kg units l ml cl g] %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price, step: 0.5 %>
  </div>

  <%= form.submit 'Save Food' %>
<% end %>

app/views/general_shopping_list/index.html.erb
<main>
  <div class="d-flex justify-content-center">
    <h1 class="list-header">Shopping List</h1>
  </div>
  <div class="d-flex total-div justify-content-center">
    <span>Amount of food items to buy: <%= @missing_items.size %> </span>
    <span>
      Total value of food needed: $
      <%= @missing_items.reduce(0) { |sum, item| sum + ((item[1] - item[0]) * item[3]) } %>
    </span>
  </div>
  <div>
    <table>
      <tr class="table-header">
        <th>Food</th>
        <th>Quantity</th>
        <th>Price($)</th>
      </tr>
      <% @missing_items.each do |item|%>
        <tr>
          <td> <%= item[2]%> </td>
          <td> <%= item[1] - item[0] %> <%= item[4] %></td>
          <td> <%= (item[1] - item[0]) * item[3] %> </td>
        </tr>
      <% end %>
    </table>
  </div>
</main>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/ingredients/edit.html.erb
<section>
  <%= form_with model: @ingredient, method: :put do |f| %>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, in: 1..100, step: 1 %>
    <%= f.submit %>
  <% end %>
</section>

app/views/ingredients/new.html.erb
<main>
  <h2>Add Ingredient</h2>
  <%= form_with model: @ingredient, url: [@recipe, @ingredient] do |f| %>
    <div>
      <%= f.label :quantity %><br>
      <%= f.number_field :quantity, in: 1..100, step: 1, value: 1 %>
    </div>
    <div>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.label :measurement_unit %><br>
      <%= f.text_field :measurement_unit, size: "80x6" %>
    </div>

    <div>
      <%= f.label :price %><br>
      <%= f.number_field :price, step: 0.5 %>
    </div>

    <%= f.submit %>
  <% end %>

</main>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/index.html.erb
<main>
  <div class="recipes">
    <h1>Recipes</h1>
    <% @recipes.each do |recipe| %>
      <%= link_to recipe_url(recipe), class: 'recipe-box' do %>
        <div>
          <h3><%= recipe.name %></h3>
          <%= button_to 'REMOVE', recipe_url(recipe), method: :delete, class: 'button' %>
        </div>
        <p><%= recipe.description %></p>
      <% end %>
    <% end %>
  </div>
</main>

app/views/recipes/new.html.erb
<h1>Recipes#new</h1>
<p>Find me in app/views/recipes/new.html.erb</p>

app/views/recipes/public_recipes.html.erb
<div class="public-recipes-container">
  <h1>Public Recipes</h1>
  <% @recipes.each do |recipe| %>
    <%= link_to recipe_url(recipe), class: 'recipe-box d-flex-column' do %>
      <div>
        <div class="d-flex" style="justify-content: space-between">
          <h3><%= recipe.name%></h3>
          <div class="d-flex d-flex-column" style="margin-right: 15rem; justify-content: space-between">
            <p>Total food items: <%= recipe.total_food_items %></p>
            <p>Total price: $<%= recipe.total_price %></p>
          </div>
        </div>
      </div>
      <h4>By: <%= recipe.user.name %></h4>
    <% end %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<main class="recipe-container">
  <h1><%= @recipe.name %></h1>
  <section class="details">
    <div>
      <p>Preparation time: <%= @recipe.preparation_time %> minutes </p>
      <p>Cooking time: <%= @recipe.cooking_time %> minutes </p>
      <p>Steps go here...</p>
      <%= link_to 'Generate shopping list', shopping_list_url, class: 'button' %>
    </div>
    <div>
      <div>
        <label for="public">Public</label>
        <input name="public" type="checkbox">
      </div>
      <%= link_to 'Add ingredient', new_recipe_ingredient_url(@recipe), class: 'button' %>
    </div>
  </section>
  <section class="ingredients">
    <table>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
      <% @recipe.ingredients.each do |ingredient| %>
        <tr>
          <td><%= ingredient.food.name %></td>
          <td><%= "#{ingredient.quantity} #{ingredient.food.measurement_unit}" %></td>
          <td>$<%= ingredient.food.price %></td>
          <td>
            <%= link_to 'Modify', edit_ingredient_url(ingredient), class: 'button' %>
            <%= link_to 'Remove', ingredient_url(ingredient), method: :delete, class: 'button' %>
          </td>
        </tr>
      <% end %>
    </table>
  </section>
</main>